spring.application.name=taskmaster-api

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmaster
spring.datasource.username=postgres
spring.datasource.password=nic123

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Swagger UI e OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html